.. |hisparc| replace:: HiSPARC
.. |monitor| replace:: HiSPARC Monitor
.. |updater| replace:: HiSPARC Updater
.. |hispdaq| replace:: HiSPARC DAQ
.. |labview| replace:: LabVIEW

.. |root| replace:: hisparc_root/

.. |buffersize| replace:: Buffer size
.. |cpuload| replace:: CPU Load
.. |discspace| replace:: Disc Space
.. |eventrate| replace:: EventRate
.. |labviewusage| replace:: LabviewUsage
.. |memoryusage| replace:: Memory Usage
.. |storagegrowth| replace:: StorageGrowth
.. |storagesize| replace:: StorageSize
.. |triggerrate| replace:: TriggerRate
.. |uptime| replace:: Uptime
